import Link from 'next/link'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'initial-scale=1, width=device-width',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div style={{ zIndex: 2000, padding: '1px', margin: '1px' }}><h3><Link href="/">CFCBerkeley Library</Link></h3></div>
        <div style={{ zIndex: 1000 }}>
          {children}
        </div>
      </body>
    </html>
  )
}
